In [2]:
import pandas as pd
import numpy as np

In [4]:
df = pd.DataFrame([['1','2','3','4'], ['a','s','d','f'], ['weq','wer','wewe','qww']],
                   columns=['k1','k2','k3','k4'], 
                   index=['x','y','xy'])
df.head(2)

  k1 k2 k3 k4
x  1  2  3  4
y  a  s  d  f

In [ ]:
# loc chce nazwy indeksu
df.loc['x']

k1    1
k2    2
k3    3
k4    4
Name: x, dtype: str

In [5]:
df.iloc[2:3]

     k1   k2    k3   k4
xy  weq  wer  wewe  qww

In [8]:
df.iloc[:,[0,1,2,3]]

     k1   k2    k3   k4
x     1    2     3    4
y     a    s     d    f
xy  weq  wer  wewe  qww

In [13]:
df.loc[df['k1']=='a']

  k1 k2 k3 k4
y  a  s  d  f

In [15]:
df.query('k2=="2"')

  k1 k2 k3 k4
x  1  2  3  4

In [16]:
df.drop(columns=['k1'])

     k2    k3   k4
x     2     3    4
y     s     d    f
xy  wer  wewe  qww

In [18]:
df['kk1'] = df['k2']+df['k3']
df

     k1   k2    k3   k4      kk1
x     1    2     3    4       23
y     a    s     d    f       sd
xy  weq  wer  wewe  qww  werwewe